Repository matheusfelipeog/happy, pull requests merged in 2020-10, with the labels that each got.

#1 Finalized landing page
  web/package.json
  web/public/index.html
  web/src/App.tsx
  web/src/images/landing.svg
  web/src/images/logo.svg
  web/src/images/map-marker.svg
  web/src/pages/Landing.tsx
  web/src/routes.tsx
  web/src/styles/global.css
  web/src/styles/pages/landing.css
  web/yarn.lock
Labels: enhancement

#2 Finalized Orphanages Map Page
  web/.gitignore
  web/package.json
  web/src/pages/OrphanagesMap.tsx
  web/src/routes.tsx
  web/src/styles/pages/orphanages-map.css
  web/yarn.lock
Labels: enhancement

#3 Feature/framer motion
  web/package.json
  web/src/pages/Landing.tsx
  web/src/styles/pages/landing.css
  web/yarn.lock
Labels: enhancement

#4 Finalized backend of happy platform
  README.md
  backend/.gitignore
  backend/ormconfig.json
  backend/package.json
  backend/src/config/upload.ts
  backend/src/controllers/OrphanagesController.ts
  backend/src/database/connection.ts
  backend/src/database/migrations/1602681187435-create_orphanages.ts
  backend/src/database/migrations/1602691088861-create_images.ts
  backend/src/errors/handler.ts
  backend/src/models/Image.ts
  backend/src/models/Orphanage.ts
  backend/src/routes.ts
  backend/src/server.ts
  backend/src/view/images_view.ts
  backend/src/view/orphanages_view.ts
  backend/tsconfig.json
  backend/yarn.lock
Labels: documentation, enhancement

#6 Added remove preview image button
  web/src/pages/CreateOrphanage.tsx
  web/src/styles/pages/create-orphanage.css
Labels: enhancement, hacktoberfest-accepted
